import { demoWorkspace } from '../data/demo-fixtures';
import type { ArtifactRecord } from './artifact-registry';
import { registerArtifact } from './artifact-registry-store';
import {
  buildAuthReadinessSnapshot,
  type AuthReadinessSnapshot,
  type AuthReadinessStatus,
} from './auth-readiness';
import type { RuntimeEnvironmentId } from './environment-registry';

const AUTH_READINESS_KEY = 'uikigai-auth-readiness-v1';

export interface AuthReadinessState {
  snapshots: AuthReadinessSnapshot[];
  artifacts: ArtifactRecord[];
  updatedAt: string;
}

function nowIso(): string {
  return new Date().toISOString();
}

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function emptyState(): AuthReadinessState {
  return { snapshots: [], artifacts: [], updatedAt: nowIso() };
}

function readState(): AuthReadinessState {
  if (typeof window === 'undefined') return emptyState();
  try {
    const raw = window.sessionStorage.getItem(AUTH_READINESS_KEY);
    if (!raw) return emptyState();
    const parsed = JSON.parse(raw) as Partial<AuthReadinessState>;
    return {
      snapshots: parsed.snapshots ?? [],
      artifacts: parsed.artifacts ?? [],
      updatedAt: parsed.updatedAt ?? nowIso(),
    };
  } catch {
    return emptyState();
  }
}

function writeState(state: AuthReadinessState) {
  if (typeof window === 'undefined') return;
  window.sessionStorage.setItem(AUTH_READINESS_KEY, JSON.stringify({ ...state, updatedAt: nowIso() }));
}

export function getAuthReadinessState(): AuthReadinessState {
  return clone(readState());
}

export function evaluateAuthReadiness(environmentId: RuntimeEnvironmentId = 'PRODUCTION'): AuthReadinessSnapshot {
  const snapshot = buildAuthReadinessSnapshot(environmentId);
  const state = readState();
  writeState({
    ...state,
    snapshots: [snapshot, ...state.snapshots.filter((entry) => entry.environmentId !== environmentId)].slice(0, 8),
  });
  return clone(snapshot);
}

export function createAuthReadinessSnapshot(environmentId: RuntimeEnvironmentId = 'PRODUCTION'): AuthReadinessSnapshot {
  return evaluateAuthReadiness(environmentId);
}

export function getAuthReadinessReport(environmentId: RuntimeEnvironmentId = 'PRODUCTION'): AuthReadinessSnapshot {
  const state = readState();
  const snapshot = state.snapshots.find((entry) => entry.environmentId === environmentId);
  return snapshot ? clone(snapshot) : evaluateAuthReadiness(environmentId);
}

function exportedArtifact(name: string, type: ArtifactRecord['type'], content: unknown): ArtifactRecord {
  const createdAt = nowIso();
  return registerArtifact({
    id: `artifact-auth-readiness-${name.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`,
    name,
    type,
    lifecycle: 'AVAILABLE',
    workspaceId: demoWorkspace.id,
    version: 1,
    metadata: {
      workspaceId: demoWorkspace.id,
      source: 'mock',
      sourceType: 'auth-readiness',
      contentSummary: `${name} generated by auth readiness layer.`,
      tags: ['auth-readiness', 'session', 'go-live'],
      sizeBytes: JSON.stringify(content).length,
    },
    createdAt,
    updatedAt: createdAt,
  });
}

export function exportAuthReadinessArtifacts(environmentId: RuntimeEnvironmentId = 'PRODUCTION'): ArtifactRecord[] {
  const report = getAuthReadinessReport(environmentId);
  const artifacts = [
    exportedArtifact('auth-readiness-report.md', 'REPORT', report),
    exportedArtifact('auth-readiness.json', 'AUDIT', report),
    exportedArtifact('session-lifecycle-report.md', 'REPORT', report.sessionLifecycle),
    exportedArtifact('token-validation-report.md', 'REPORT', report.tokenValidation),
    exportedArtifact('rbac-binding-report.md', 'REPORT', report.rbacBinding),
    exportedArtifact('tenant-workspace-binding-report.md', 'REPORT', report.tenantWorkspaceBinding),
    exportedArtifact('auth-blockers.json', 'AUDIT', report.blockers),
  ];
  const state = readState();
  writeState({ ...state, artifacts });
  return clone(artifacts);
}

export function getAuthReadinessArtifacts(): ArtifactRecord[] {
  return clone(readState().artifacts);
}

export function selectAuthReadiness() {
  return getAuthReadinessReport('PRODUCTION');
}

export function selectAuthReadinessStatus(): AuthReadinessStatus {
  return getAuthReadinessReport('PRODUCTION').status;
}

export function selectAuthReadinessScore() {
  return getAuthReadinessReport('PRODUCTION').readinessScore;
}

export function selectAuthBlockers() {
  return getAuthReadinessReport('PRODUCTION').blockers;
}

export function selectAuthWarnings() {
  return getAuthReadinessReport('PRODUCTION').warnings;
}

export function selectSessionLifecycleStatus() {
  return getAuthReadinessReport('PRODUCTION').sessionLifecycle;
}

export function selectTokenValidationStatus() {
  return getAuthReadinessReport('PRODUCTION').tokenValidation;
}

export function selectRbacBindingStatus() {
  return getAuthReadinessReport('PRODUCTION').rbacBinding;
}

export function selectTenantWorkspaceBindingStatus() {
  return getAuthReadinessReport('PRODUCTION').tenantWorkspaceBinding;
}
