import { demoWorkspace } from '../data/demo-fixtures';
import type { ArtifactRecord } from './artifact-registry';
import { registerArtifact } from './artifact-registry-store';
import {
  buildEnvironmentReadinessReport,
  getRequiredProductionEnvMatrix,
  type EnvironmentReadinessReport,
  type EnvironmentReadinessStatus,
} from './environment-readiness';
import type { RuntimeEnvironmentId } from './environment-registry';
import { filterReadinessBlockersForEvidence } from './production-config-evidence-store';

const ENVIRONMENT_READINESS_KEY = 'uikigai-environment-readiness-v1';

export interface EnvironmentReadinessState {
  reports: EnvironmentReadinessReport[];
  artifacts: ArtifactRecord[];
  updatedAt: string;
}

function nowIso(): string {
  return new Date().toISOString();
}

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function emptyState(): EnvironmentReadinessState {
  return { reports: [], artifacts: [], updatedAt: nowIso() };
}

function readState(): EnvironmentReadinessState {
  if (typeof window === 'undefined') return emptyState();
  try {
    const raw = window.sessionStorage.getItem(ENVIRONMENT_READINESS_KEY);
    if (!raw) return emptyState();
    const parsed = JSON.parse(raw) as Partial<EnvironmentReadinessState>;
    return {
      reports: parsed.reports ?? [],
      artifacts: parsed.artifacts ?? [],
      updatedAt: parsed.updatedAt ?? nowIso(),
    };
  } catch {
    return emptyState();
  }
}

function writeState(state: EnvironmentReadinessState) {
  if (typeof window === 'undefined') return;
  window.sessionStorage.setItem(ENVIRONMENT_READINESS_KEY, JSON.stringify({ ...state, updatedAt: nowIso() }));
}

export function getEnvironmentReadinessState(): EnvironmentReadinessState {
  return clone(readState());
}

export function evaluateEnvironmentReadiness(
  environmentId: RuntimeEnvironmentId = 'PRODUCTION',
  providedValues?: Record<string, string | undefined>,
): EnvironmentReadinessReport {
  const report = buildEnvironmentReadinessReport(environmentId, providedValues);
  const state = readState();
  writeState({
    ...state,
    reports: [report, ...state.reports.filter((entry) => entry.environmentId !== environmentId)].slice(0, 8),
  });
  return clone(report);
}

export function createEnvironmentReadinessSnapshot(environmentId: RuntimeEnvironmentId = 'PRODUCTION'): EnvironmentReadinessReport {
  return evaluateEnvironmentReadiness(environmentId);
}

export function getEnvironmentReadinessReport(environmentId: RuntimeEnvironmentId = 'PRODUCTION'): EnvironmentReadinessReport {
  const state = readState();
  const report = state.reports.find((entry) => entry.environmentId === environmentId);
  return report ? clone(report) : evaluateEnvironmentReadiness(environmentId);
}

export function getEvidenceAdjustedEnvironmentReadinessReport(environmentId: RuntimeEnvironmentId = 'PRODUCTION'): EnvironmentReadinessReport {
  const report = getEnvironmentReadinessReport(environmentId);
  if (environmentId !== 'PRODUCTION') return report;
  const blockers = filterReadinessBlockersForEvidence('environment-readiness', report.blockers);
  return {
    ...report,
    blockers,
    status: blockers.length ? report.status : report.warnings.length ? 'WARNING' : 'READY',
    readinessScore: blockers.length ? report.readinessScore : Math.max(report.readinessScore, 78),
  };
}

function exportedArtifact(name: string, type: ArtifactRecord['type'], content: unknown): ArtifactRecord {
  const createdAt = nowIso();
  return registerArtifact({
    id: `artifact-environment-readiness-${name.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`,
    name,
    type,
    lifecycle: 'AVAILABLE',
    workspaceId: demoWorkspace.id,
    version: 1,
    metadata: {
      workspaceId: demoWorkspace.id,
      source: 'mock',
      sourceType: 'environment-readiness',
      contentSummary: `${name} generated by environment readiness layer. Raw secret values are excluded.`,
      tags: ['environment-readiness', 'secret-readiness', 'go-live'],
      sizeBytes: JSON.stringify(content).length,
    },
    createdAt,
    updatedAt: createdAt,
  });
}

export function exportEnvironmentReadinessArtifacts(environmentId: RuntimeEnvironmentId = 'PRODUCTION'): ArtifactRecord[] {
  const report = getEnvironmentReadinessReport(environmentId);
  const artifacts = [
    exportedArtifact('environment-readiness-report.md', 'REPORT', report),
    exportedArtifact('environment-readiness.json', 'AUDIT', report),
    exportedArtifact('secret-readiness-report.md', 'REPORT', { status: report.secretStatus, checks: report.secrets }),
    exportedArtifact('missing-production-env.json', 'AUDIT', report.missingRequired),
    exportedArtifact('secret-rotation-evidence.md', 'REPORT', report.rotationStatus),
    exportedArtifact('production-config-blockers.json', 'AUDIT', report.blockers),
  ];
  const state = readState();
  writeState({ ...state, artifacts });
  return clone(artifacts);
}

export function getEnvironmentReadinessArtifacts(): ArtifactRecord[] {
  return clone(readState().artifacts);
}

export function selectEnvironmentReadiness() {
  return getEnvironmentReadinessReport('PRODUCTION');
}

export function selectEnvironmentReadinessStatus(): EnvironmentReadinessStatus {
  return getEnvironmentReadinessReport('PRODUCTION').status;
}

export function selectEnvironmentReadinessScore() {
  return getEnvironmentReadinessReport('PRODUCTION').readinessScore;
}

export function selectEnvironmentReadinessBlockers() {
  return getEnvironmentReadinessReport('PRODUCTION').blockers;
}

export function selectEnvironmentReadinessWarnings() {
  return getEnvironmentReadinessReport('PRODUCTION').warnings;
}

export function selectSecretReadiness() {
  return getEnvironmentReadinessReport('PRODUCTION').secrets;
}

export function selectSecretReadinessStatus() {
  return getEnvironmentReadinessReport('PRODUCTION').secretStatus;
}

export function selectRequiredProductionEnvMatrix() {
  return getRequiredProductionEnvMatrix();
}

export function selectMaskedEnvironmentVariables() {
  return getEnvironmentReadinessReport('PRODUCTION').variables;
}
