import { demoWorkspace } from '../data/demo-fixtures';
import type { ArtifactRecord } from './artifact-registry';
import { registerArtifact } from './artifact-registry-store';
import {
  PRODUCTION_EVIDENCE_CATEGORIES,
  buildProductionEvidenceDashboard,
  filterReadinessBlockersWithEvidence,
  getProductionEvidenceRequirement,
  getProductionEvidenceRequirements,
  getVerifiedProductionEvidenceCategories,
  isProductionEvidenceExpired,
  sanitizeProductionEvidenceInput,
  validateProductionEvidenceInput,
  type ProductionConfigEvidence,
  type ProductionConfigEvidenceInput,
  type ProductionEvidenceCategory,
  type ProductionEvidenceDashboard,
  type ProductionEvidenceStatus,
} from './production-config-evidence';
import { selectObservabilityDashboard } from './production-observability-store';

const PRODUCTION_CONFIG_EVIDENCE_KEY = 'uikigai-production-config-evidence-v1';

export interface ProductionConfigEvidenceState {
  evidence: ProductionConfigEvidence[];
  artifacts: ArtifactRecord[];
  updatedAt: string;
}

function nowIso(): string {
  return new Date().toISOString();
}

function unique(prefix: string): string {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function emptyState(): ProductionConfigEvidenceState {
  return { evidence: [], artifacts: [], updatedAt: nowIso() };
}

function readState(): ProductionConfigEvidenceState {
  if (typeof window === 'undefined') return emptyState();
  try {
    const raw = window.sessionStorage.getItem(PRODUCTION_CONFIG_EVIDENCE_KEY);
    if (!raw) return emptyState();
    const parsed = JSON.parse(raw) as Partial<ProductionConfigEvidenceState>;
    return {
      evidence: parsed.evidence ?? [],
      artifacts: parsed.artifacts ?? [],
      updatedAt: parsed.updatedAt ?? nowIso(),
    };
  } catch {
    return emptyState();
  }
}

function writeState(state: ProductionConfigEvidenceState) {
  if (typeof window === 'undefined') return;
  window.sessionStorage.setItem(PRODUCTION_CONFIG_EVIDENCE_KEY, JSON.stringify({ ...state, updatedAt: nowIso() }));
}

function patchEvidence(id: string, patch: Partial<ProductionConfigEvidence>): ProductionConfigEvidence | undefined {
  const state = readState();
  const evidence = state.evidence.map((entry) => entry.id === id ? { ...entry, ...patch } : entry);
  const updated = evidence.find((entry) => entry.id === id);
  writeState({ ...state, evidence });
  return updated ? clone(updated) : undefined;
}

function exportedArtifact(name: string, type: ArtifactRecord['type'], content: unknown): ArtifactRecord {
  const createdAt = nowIso();
  return registerArtifact({
    id: `artifact-production-config-evidence-${name.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`,
    name,
    type,
    lifecycle: 'AVAILABLE',
    workspaceId: demoWorkspace.id,
    version: 1,
    metadata: {
      workspaceId: demoWorkspace.id,
      source: 'mock',
      sourceType: 'production-config-evidence',
      contentSummary: `${name} generated by production config evidence binder. Raw secret values are excluded.`,
      tags: ['production-config-evidence', 'go-live', 'redacted'],
      sizeBytes: JSON.stringify(content).length,
    },
    createdAt,
    updatedAt: createdAt,
  });
}

export function getProductionConfigEvidenceState(): ProductionConfigEvidenceState {
  return clone(readState());
}

export function addEvidence(input: ProductionConfigEvidenceInput): ProductionConfigEvidence {
  const sanitized = sanitizeProductionEvidenceInput(input);
  const record: ProductionConfigEvidence = {
    id: unique(`production-evidence-${input.category}`),
    providedAt: nowIso(),
    ...sanitized,
  };
  const state = readState();
  writeState({ ...state, evidence: [record, ...state.evidence].slice(0, 80) });
  return clone(record);
}

export function verifyEvidence(id: string, verificationMethod = 'manual_review'): ProductionConfigEvidence | undefined {
  const state = readState();
  const evidence = state.evidence.find((entry) => entry.id === id);
  if (!evidence) return undefined;
  const warnings = validateProductionEvidenceInput({
    category: evidence.category,
    environment: evidence.environment,
    evidenceType: evidence.evidenceType,
    description: evidence.description,
    source: evidence.source,
    providedBy: evidence.providedBy,
    maskedValue: evidence.maskedValue,
    expiresAt: evidence.expiresAt,
    metadata: evidence.metadata,
  });
  if (warnings.some((warning) => /invalid|unsafe|missing|required/i.test(warning))) {
    return patchEvidence(id, {
      status: 'rejected',
      severity: 'critical',
      warnings: Array.from(new Set([...evidence.warnings, ...warnings])),
      verificationMethod,
      verifiedAt: undefined,
    });
  }
  if (isProductionEvidenceExpired(evidence)) {
    return patchEvidence(id, {
      status: 'expired',
      warnings: Array.from(new Set([...evidence.warnings, 'Evidence expired before verification.'])),
    });
  }
  return patchEvidence(id, {
    status: 'verified',
    verifiedAt: nowIso(),
    verificationMethod,
    warnings,
  });
}

export function rejectEvidence(id: string, reason = 'Evidence rejected by reviewer.'): ProductionConfigEvidence | undefined {
  return patchEvidence(id, {
    status: 'rejected',
    severity: 'critical',
    warnings: [reason],
    verifiedAt: undefined,
  });
}

export function expireEvidence(id: string): ProductionConfigEvidence | undefined {
  return patchEvidence(id, {
    status: 'expired',
    expiresAt: nowIso(),
    warnings: ['Evidence was expired and no longer unlocks production gates.'],
  });
}

export function clearProductionConfigEvidence() {
  if (typeof window === 'undefined') return;
  window.sessionStorage.removeItem(PRODUCTION_CONFIG_EVIDENCE_KEY);
}

export function getProductionConfigEvidenceByCategory(category: ProductionEvidenceCategory): ProductionConfigEvidence[] {
  return clone(readState().evidence.filter((entry) => entry.category === category));
}

export function selectProductionConfigEvidenceDashboard(): ProductionEvidenceDashboard {
  return clone(buildProductionEvidenceDashboard(readState().evidence));
}

export function selectProductionConfigEvidence(): ProductionConfigEvidence[] {
  return clone(readState().evidence);
}

export function selectEvidenceByCategory(category: ProductionEvidenceCategory): ProductionConfigEvidence[] {
  return getProductionConfigEvidenceByCategory(category);
}

export function selectMissingProductionEvidence() {
  return clone(selectProductionConfigEvidenceDashboard().missing);
}

export function selectVerifiedProductionEvidence() {
  return clone(selectProductionConfigEvidenceDashboard().verified);
}

export function selectRejectedProductionEvidence() {
  return clone(selectProductionConfigEvidenceDashboard().rejected);
}

export function selectExpiredProductionEvidence() {
  return clone(selectProductionConfigEvidenceDashboard().expired);
}

export function selectEvidenceResolvedBlockers() {
  return clone(selectProductionConfigEvidenceDashboard().resolvedBlockers);
}

export function selectEvidenceRemainingBlockers() {
  return clone(selectProductionConfigEvidenceDashboard().remainingBlockers);
}

export function selectProductionEvidenceReadinessScore() {
  return selectProductionConfigEvidenceDashboard().readinessScore;
}

export function selectProductionEvidenceVerdict() {
  return selectProductionConfigEvidenceDashboard().verdict;
}

export function getVerifiedProductionEvidenceCategorySet() {
  return getVerifiedProductionEvidenceCategories(readState().evidence);
}

export function filterReadinessBlockersForEvidence(gateId: string, blockers: string[]): string[] {
  return filterReadinessBlockersWithEvidence(gateId, blockers, getVerifiedProductionEvidenceCategorySet());
}

export function getProductionEvidenceStatusForCategory(category: ProductionEvidenceCategory): ProductionEvidenceStatus {
  const dashboard = selectProductionConfigEvidenceDashboard();
  if (dashboard.verified.some((entry) => entry.category === category)) return 'verified';
  if (dashboard.expired.some((entry) => entry.category === category)) return 'expired';
  if (dashboard.rejected.some((entry) => entry.category === category)) return 'rejected';
  if (dashboard.provided.some((entry) => entry.category === category)) return 'provided';
  return 'missing';
}

export function exportProductionConfigEvidencePack(): ArtifactRecord[] {
  const dashboard = selectProductionConfigEvidenceDashboard();
  const observability = selectObservabilityDashboard();
  const redactedEvidence = dashboard.evidence.map((entry) => ({
    ...entry,
    metadata: entry.metadata ? Object.fromEntries(Object.entries(entry.metadata).map(([key, value]) => [key, typeof value === 'string' && /secret|token|password|key/i.test(key) ? '***redacted***' : value])) : undefined,
  }));
  const artifacts = [
    exportedArtifact('production-config-evidence.json', 'AUDIT', redactedEvidence),
    exportedArtifact('production-config-evidence-summary.md', 'REPORT', dashboard),
    exportedArtifact('production-evidence-blockers.json', 'AUDIT', dashboard.remainingBlockers),
    exportedArtifact('production-evidence-redaction-report.md', 'REPORT', {
      policy: 'Raw secrets are never stored. Values are masked at ingestion and exports contain masked evidence only.',
      evidenceCount: redactedEvidence.length,
    }),
    exportedArtifact('production-go-live-evidence-pack.md', 'REPORT', {
      verdict: dashboard.verdict,
      readinessScore: dashboard.readinessScore,
      resolvedBlockers: dashboard.resolvedBlockers,
      remainingBlockers: dashboard.remainingBlockers,
      observabilityVerdict: observability.verdict,
      observabilityScore: observability.readinessScore,
    }),
    exportedArtifact('production-config-final-verdict.md', 'REPORT', dashboard.verdict),
  ];
  const state = readState();
  writeState({ ...state, artifacts });
  return clone(artifacts);
}

export function getProductionConfigEvidenceArtifacts(): ArtifactRecord[] {
  return clone(readState().artifacts);
}

export function createDemoEvidenceInput(category: ProductionEvidenceCategory): ProductionConfigEvidenceInput {
  const base = {
    category,
    environment: 'PRODUCTION' as const,
    evidenceType: 'attestation',
    description: `${getProductionEvidenceRequirement(category).label} evidence for production readiness.`,
    source: 'operator',
    providedBy: 'platform',
  };
  if (category === 'backend_endpoint' || category === 'production_endpoint_reachability') {
    return { ...base, rawValue: 'https://api.uikigai.example.com' };
  }
  if (category === 'database_config') {
    return { ...base, rawValue: 'postgres://prod-user:prod-password@db.example.com/growthos', metadata: { provider: 'postgres' } };
  }
  if (category === 'auth_config') {
    return {
      ...base,
      rawValue: 'auth0-production-config',
      metadata: { provider: 'auth0', issuer: 'https://issuer.example.com', audience: 'growthos', tokenMode: 'jwt', sessionMode: 'cookie' },
    };
  }
  if (category === 'secret_presence') {
    return { ...base, rawValue: 'secret-exists-in-vault', metadata: { presenceConfirmed: true } };
  }
  return { ...base, rawValue: `${category}-proof` };
}

export function addNextMissingDemoEvidence(): ProductionConfigEvidence {
  const dashboard = selectProductionConfigEvidenceDashboard();
  const category = dashboard.missing[0]?.category ?? PRODUCTION_EVIDENCE_CATEGORIES[0];
  return addEvidence(createDemoEvidenceInput(category));
}

export function verifyFirstProvidedEvidence(): ProductionConfigEvidence | undefined {
  const evidence = readState().evidence.find((entry) => entry.status === 'provided');
  return evidence ? verifyEvidence(evidence.id, 'operator_review') : undefined;
}

export function rejectFirstReviewableEvidence(): ProductionConfigEvidence | undefined {
  const evidence = readState().evidence.find((entry) => entry.status === 'provided' || entry.status === 'verified');
  return evidence ? rejectEvidence(evidence.id) : undefined;
}

export function expireFirstVerifiedEvidence(): ProductionConfigEvidence | undefined {
  const evidence = readState().evidence.find((entry) => entry.status === 'verified');
  return evidence ? expireEvidence(evidence.id) : undefined;
}

export { getProductionEvidenceRequirements };
