import { demoWorkspace } from '../data/demo-fixtures';
import type { ArtifactRecord } from './artifact-registry';
import { registerArtifact } from './artifact-registry-store';
import {
  buildProductionObservabilityDashboard,
  validateHealthMonitor,
  type AlertChannelInput,
  type HealthMonitorInput,
  type IncidentOwnerInput,
  type ProductionObservabilityCheck,
  type ProductionObservabilityDashboard,
  type ProductionObservabilityStatus,
} from './production-observability';

const PRODUCTION_OBSERVABILITY_KEY = 'uikigai-production-observability-v1';

export interface ProductionObservabilityState {
  checks: ProductionObservabilityCheck[];
  artifacts: ArtifactRecord[];
  updatedAt: string;
}

function nowIso(): string {
  return new Date().toISOString();
}

function unique(prefix: string): string {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function emptyState(): ProductionObservabilityState {
  return { checks: [], artifacts: [], updatedAt: nowIso() };
}

function readState(): ProductionObservabilityState {
  if (typeof window === 'undefined') return emptyState();
  try {
    const raw = window.sessionStorage.getItem(PRODUCTION_OBSERVABILITY_KEY);
    if (!raw) return emptyState();
    const parsed = JSON.parse(raw) as Partial<ProductionObservabilityState>;
    return {
      checks: parsed.checks ?? [],
      artifacts: parsed.artifacts ?? [],
      updatedAt: parsed.updatedAt ?? nowIso(),
    };
  } catch {
    return emptyState();
  }
}

function writeState(state: ProductionObservabilityState) {
  if (typeof window === 'undefined') return;
  window.sessionStorage.setItem(PRODUCTION_OBSERVABILITY_KEY, JSON.stringify({ ...state, updatedAt: nowIso() }));
}

function persistCheck(check: ProductionObservabilityCheck): ProductionObservabilityCheck {
  const state = readState();
  const checks = [check, ...state.checks.filter((entry) => entry.id !== check.id)].slice(0, 80);
  writeState({ ...state, checks });
  return clone(check);
}

function patchCheck(id: string, patch: Partial<ProductionObservabilityCheck>): ProductionObservabilityCheck | undefined {
  const state = readState();
  const checks = state.checks.map((entry) => entry.id === id ? { ...entry, ...patch } : entry);
  const updated = checks.find((entry) => entry.id === id);
  writeState({ ...state, checks });
  return updated ? clone(updated) : undefined;
}

function check(type: ProductionObservabilityCheck['type'], name: string, description: string, source: string, metadata?: Record<string, unknown>, evidence: string[] = []): ProductionObservabilityCheck {
  return {
    id: unique(`production-observability-${type}`),
    type,
    name,
    environment: 'PRODUCTION',
    status: 'configured',
    severity: ['health_monitor', 'alert_channel', 'incident_owner', 'runbook', 'slo_sla', 'rto_rpo'].includes(type) ? 'critical' : 'blocker',
    description,
    source,
    configuredAt: nowIso(),
    evidence,
    warnings: [],
    metadata,
  };
}

function exportedArtifact(name: string, type: ArtifactRecord['type'], content: unknown): ArtifactRecord {
  const createdAt = nowIso();
  return registerArtifact({
    id: `artifact-production-observability-${name.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`,
    name,
    type,
    lifecycle: 'AVAILABLE',
    workspaceId: demoWorkspace.id,
    version: 1,
    metadata: {
      workspaceId: demoWorkspace.id,
      source: 'mock',
      sourceType: 'production-observability',
      contentSummary: `${name} generated by production observability readiness layer. Raw secrets are excluded.`,
      tags: ['production-observability', 'incident-readiness', 'go-live'],
      sizeBytes: JSON.stringify(content).length,
    },
    createdAt,
    updatedAt: createdAt,
  });
}

export function getProductionObservabilityState(): ProductionObservabilityState {
  return clone(readState());
}

export function clearProductionObservability() {
  if (typeof window === 'undefined') return;
  window.sessionStorage.removeItem(PRODUCTION_OBSERVABILITY_KEY);
}

export function addMonitorEvidence(input: HealthMonitorInput): ProductionObservabilityCheck {
  const warnings = validateHealthMonitor(input);
  return persistCheck({
    ...check('health_monitor', input.name, 'Synthetic production health monitor evidence.', 'observability-platform', {
      endpoint: input.endpoint.replace(/\/\/.*@/, '//***@'),
      uptimePercent: input.uptimePercent,
      latencyMs: input.latencyMs,
      errorRatePercent: input.errorRatePercent,
    }, [`uptime=${input.uptimePercent}`, `latency=${input.latencyMs}`, `errorRate=${input.errorRatePercent}`]),
    status: warnings.length ? 'blocked' : 'configured',
    warnings,
  });
}

export function verifyMonitorEvidence(id: string, verifiedBy = 'synthetic_check'): ProductionObservabilityCheck | undefined {
  const state = readState();
  const existing = state.checks.find((entry) => entry.id === id);
  if (!existing) return undefined;
  if (existing.type === 'health_monitor' && existing.warnings.length) {
    return patchCheck(id, { status: 'failed', verifiedBy, verifiedAt: nowIso() });
  }
  return patchCheck(id, { status: 'verified', verifiedBy, verifiedAt: nowIso(), warnings: [] });
}

export function rejectMonitorEvidence(id: string, reason = 'Monitor evidence rejected by operator review.'): ProductionObservabilityCheck | undefined {
  return patchCheck(id, { status: 'failed', warnings: [reason], verifiedAt: undefined });
}

export function addAlertChannel(input: AlertChannelInput): ProductionObservabilityCheck {
  return persistCheck(check('alert_channel', input.name, 'Production alert channel evidence.', 'incident-platform', {
    channelType: input.channelType,
    target: input.target,
  }, [`channel=${input.channelType}`, `target=${input.target}`]));
}

export function testAlertChannel(id: string): ProductionObservabilityCheck | undefined {
  return patchCheck(id, { status: 'verified', verifiedAt: nowIso(), verifiedBy: 'alert_test' });
}

export function addIncidentOwner(input: IncidentOwnerInput): ProductionObservabilityCheck {
  const owner = persistCheck({
    ...check('incident_owner', input.name, 'Production incident response owner evidence.', 'incident-management', {
      team: input.team,
    }, [`team=${input.team}`, `owner=${input.name}`]),
    status: 'verified',
    verifiedAt: nowIso(),
    verifiedBy: 'incident_owner_registry',
  });
  persistCheck({
    ...check('escalation_policy', input.escalationPolicy, 'Production escalation policy evidence.', 'incident-management', {
      ownerId: owner.id,
    }, [`policy=${input.escalationPolicy}`]),
    status: 'verified',
    verifiedAt: nowIso(),
    verifiedBy: 'incident_owner_registry',
  });
  return owner;
}

export function verifyRunbook(): ProductionObservabilityCheck[] {
  const checks = [
    check('runbook', 'Production rollback runbook', 'Rollback and incident runbook evidence is available.', 'runbook-repository', { version: '2026.06', reviewedBy: 'SRE' }, ['rollback-runbook=v2026.06']),
    check('logging', 'Production structured logging', 'Application logs are routed to centralized production logging.', 'logging-platform', { destination: 'centralized-log-store' }, ['logs=centralized']),
    check('audit_logging', 'Production audit trail', 'Audit logs are retained and queryable for go-live operations.', 'audit-platform', { retentionDays: 365 }, ['audit-retention=365d']),
    check('slo_sla', 'Production SLO/SLA thresholds', 'SLO/SLA thresholds exist for uptime, latency, and error rate.', 'observability-platform', { uptime: 99.9, latencyMs: 500, errorRatePercent: 1 }, ['uptime>=99.9', 'p95<=500ms', 'errorRate<=1%']),
    check('rto_rpo', 'Production RTO/RPO targets', 'Recovery objectives are documented and reviewed.', 'sre-runbook', { rtoMinutes: 60, rpoMinutes: 15 }, ['rto=60m', 'rpo=15m']),
    check('dashboard', 'Production observability dashboard', 'Production dashboard is available for launch monitoring.', 'observability-platform', { dashboardUrl: 'https://observability.example.com/growthos' }, ['dashboard=available']),
  ].map((entry) => ({ ...entry, status: 'verified' as ProductionObservabilityStatus, verifiedAt: nowIso(), verifiedBy: 'operator_review' }));
  checks.forEach(persistCheck);
  return clone(checks);
}

export function selectObservabilityDashboard(): ProductionObservabilityDashboard {
  return clone(buildProductionObservabilityDashboard(readState().checks));
}

export function selectProductionObservability() {
  return clone(readState().checks);
}

export function selectObservabilityHealthMatrix() {
  return selectObservabilityDashboard().healthMatrix;
}

export function selectObservabilityBlockers() {
  return selectObservabilityDashboard().blockers;
}

export function selectObservabilityWarnings() {
  return selectObservabilityDashboard().warnings;
}

export function selectAlertChannelReadiness() {
  return selectObservabilityDashboard().alertChannelStatus;
}

export function selectIncidentOwnerReadiness() {
  return selectObservabilityDashboard().incidentOwnerStatus;
}

export function selectRunbookReadiness() {
  return selectObservabilityDashboard().runbookStatus;
}

export function selectSloSlaReadiness() {
  return selectObservabilityDashboard().sloSlaStatus;
}

export function selectRtoRpoReadiness() {
  return selectObservabilityDashboard().rtoRpoStatus;
}

export function selectProductionObservabilityScore() {
  return selectObservabilityDashboard().readinessScore;
}

export function selectProductionObservabilityVerdict() {
  return selectObservabilityDashboard().verdict;
}

export function exportObservabilityPack(): ArtifactRecord[] {
  const dashboard = selectObservabilityDashboard();
  const artifacts = [
    exportedArtifact('production-observability-report.md', 'REPORT', dashboard),
    exportedArtifact('production-observability.json', 'AUDIT', dashboard.checks),
    exportedArtifact('production-alert-readiness.md', 'REPORT', { status: dashboard.alertChannelStatus, alertChannels: dashboard.alertChannels }),
    exportedArtifact('production-incident-runbook.md', 'REPORT', { owners: dashboard.incidentOwners, runbooks: dashboard.runbooks }),
    exportedArtifact('production-slo-sla-report.md', 'REPORT', { status: dashboard.sloSlaStatus, checks: dashboard.sloSlaChecks }),
    exportedArtifact('production-rto-rpo-report.md', 'REPORT', { status: dashboard.rtoRpoStatus, checks: dashboard.rtoRpoChecks }),
    exportedArtifact('production-observability-blockers.json', 'AUDIT', dashboard.blockers),
  ];
  const state = readState();
  writeState({ ...state, artifacts });
  return clone(artifacts);
}

export function getProductionObservabilityArtifacts(): ArtifactRecord[] {
  return clone(readState().artifacts);
}

export function addDemoMonitorEvidence() {
  return addMonitorEvidence({
    name: 'Production API monitor',
    endpoint: 'https://api.uikigai.example.com/health',
    uptimePercent: 99.95,
    latencyMs: 180,
    errorRatePercent: 0.05,
  });
}

export function verifyFirstConfiguredMonitor() {
  const monitor = readState().checks.find((entry) => entry.type === 'health_monitor' && entry.status === 'configured');
  return monitor ? verifyMonitorEvidence(monitor.id, 'operator_review') : undefined;
}

export function rejectFirstMonitor() {
  const monitor = readState().checks.find((entry) => entry.type === 'health_monitor' && ['configured', 'verified'].includes(entry.status));
  return monitor ? rejectMonitorEvidence(monitor.id) : undefined;
}

export function addDemoAlertChannel() {
  return addAlertChannel({ name: 'PagerDuty primary', channelType: 'pagerduty', target: 'pd-prod-escalation' });
}

export function testFirstAlertChannel() {
  const channel = readState().checks.find((entry) => entry.type === 'alert_channel' && entry.status === 'configured');
  return channel ? testAlertChannel(channel.id) : undefined;
}

export function addDemoIncidentOwner() {
  return addIncidentOwner({ name: 'Platform on-call', team: 'SRE', escalationPolicy: 'sev1-primary-secondary' });
}
